Added Issue Template and Pull Request template
kaustubhgupta/PortfolioFy pull request #22
Opened 2021-02-01 10:14 UTC by deytulsi18

Added Issue Template and Pull Request template, PR with reference to #20

2021-02-01 10:14 UTC, deytulsi18 commented
Please review and merge the PR.

2021-02-02 09:12 UTC, kaustubhgupta requested changes

2021-02-02 09:12 UTC, kaustubhgupta commented on .github/ISSUE_TEMPLATE/bug_report.md
> +---
This is unnecessary, you can remove this (line 1 to 18)

2021-02-02 09:12 UTC, kaustubhgupta commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**To Reproduce**
```suggestion
** Steps to reproduce the bug**
```

2021-02-02 09:12 UTC, kaustubhgupta commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Steps to reproduce the behavior:
Remove this line

2021-02-02 09:12 UTC, kaustubhgupta commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Actual behavior**
write w.r.t in full words (with respect to)

2021-02-02 09:12 UTC, kaustubhgupta commented on .github/ISSUE_TEMPLATE/feature_request.md
> +---
Same instructions for this template

2021-02-02 09:12 UTC, kaustubhgupta commented on .github/ISSUE_TEMPLATE/feature_request.md
> +**Describe alternatives you've considered**
You can remove this header and associated text with this (next line)

2021-02-02 09:12 UTC, kaustubhgupta commented on .github/pull_request_template.md
> +- issue goes here
```suggestion
- Fixes: #
```

2021-02-02 09:12 UTC, kaustubhgupta commented on .github/pull_request_template.md
> +# Checklist
For now, remove this checklist

2021-02-02 09:12 UTC, kaustubhgupta commented on .github/pull_request_template.md
> +Original             |  Updated
Remove this table, only screenshots header is fine

2021-02-02 09:31 UTC, deytulsi18 commented
OK, making the necessary changes

2021-02-02 10:09 UTC, deytulsi18 commented
Kindly review the newly made changes.

2021-02-03 16:36 UTC, kaustubhgupta requested changes

2021-02-03 16:36 UTC, kaustubhgupta commented on .github/pull_request_template.md
> +Original             |  Updated
Remove this line too

2021-02-07 09:34 UTC, kaustubhgupta commented
@deytulsi18 Have a look at the new requested changes if you haven't already

2021-02-08 10:42 UTC, closed without merging

2021-02-08 10:43 UTC, kaustubhgupta commented
Due to inactivity, this PR is closed. Also, I no longer need any template for this repo!